// TurboQuant TQ4_0_WHT flash attention vec kernel instances.

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_TQ4_0_WHT, GGML_TYPE_F16);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_TQ4_0_WHT, GGML_TYPE_F16);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_TQ4_0_WHT, GGML_TYPE_F16);
