#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_TQ3_0_WHT, GGML_TYPE_TQ3_0_WHT);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_TQ3_0_WHT, GGML_TYPE_TQ3_0_WHT);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_TQ3_0_WHT, GGML_TYPE_TQ3_0_WHT);
